app = "n8n-kusmedios"
primary_region = "dfw"

[build]
  image = "n8nio/n8n:latest"

[env]
  N8N_HOST = "n8n-kusmedios.fly.dev"
  N8N_PORT = "5678"
  N8N_PROTOCOL = "https"
  WEBHOOK_URL = "https://n8n-kusmedios.fly.dev/"
  N8N_EDITOR_BASE_URL = "https://n8n-kusmedios.fly.dev/"
  GENERIC_TIMEZONE = "America/Mexico_City"
  N8N_LOG_LEVEL = "warn"
  N8N_METRICS = "false"
  EXECUTIONS_PROCESS = "main"
  N8N_PUSH_BACKEND = "websocket"
  DB_TYPE = "sqlite"
  N8N_USER_FOLDER = "/home/node/.n8n"
  EXECUTIONS_DATA_PRUNE = "true"
  EXECUTIONS_DATA_MAX_AGE = "720"

[[services]]
  protocol = "tcp"
  internal_port = 5678

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 40

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "60s"

[[mounts]]
  source = "n8n_data"
  destination = "/home/node/.n8n"

[vm]
  memory = "2048mb"
  cpu_kind = "shared"
  cpus = 2
